### ISSUE TITLE
remove import DevInt to support tango>=9.5.0

### ISSUE THREAD

**Issue by hollatz** [MBI-Div-B/sardana-MbiTangoMotorController#2]
With tango 9.5.0, the type DevInt was removed.
MbiTangoMotorController imports DevInt, but as far as I can see in the source code, it is not needed.
Remove the import DevInt to support tango>=9.5.0.

**Comment by dschick** [comment]
solved via 0df1c5a136733174bf85c3de5462d8fab38369ff
